version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fly-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend/fly-with-me
    container_name: fly-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
